require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pal0' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'react-native-voice', :path => '../node_modules/react-native-voice'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-aes', :path => '../node_modules/react-native-aes-crypto'

  target 'pal0Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'pal0-tvOS' do
  # Pods for pal0-tvOS

  target 'pal0-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
